# Generated by Django 4.2.6 on 2023-11-02 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_student', to='student.student'),
        ),
        migrations.AlterField(
            model_name='studentrating',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='student.student'),
        ),
    ]
