# Generated by Django 4.2.6 on 2023-12-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_alter_classroom_student_alter_studentrating_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutordetail',
            name='diploma_file',
            field=models.FileField(blank=True, null=True, upload_to='diploma-files'),
        ),
        migrations.AddField(
            model_name='tutordetail',
            name='diploma_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tutordetail',
            name='discipline',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='tutordetail',
            name='education_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tutordetail',
            name='funfact',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tutordetail',
            name='hobbies',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tutordetail',
            name='linkedin',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tutordetail',
            name='proficiency_test_file',
            field=models.FileField(blank=True, null=True, upload_to='diploma-files'),
        ),
        migrations.AddField(
            model_name='tutordetail',
            name='proficiency_test_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tutordetail',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile-pictures'),
        ),
        migrations.AddField(
            model_name='tutordetail',
            name='university_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
