# Generated by Django 4.2.6 on 2023-12-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_tutordetail_diploma_file_tutordetail_diploma_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroom',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
