# Generated by Django 4.2.6 on 2024-01-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_dispute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='completed',
        ),
        migrations.AddField(
            model_name='classroom',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=50),
        ),
    ]
