# Generated by Django 4.2.6 on 2024-01-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0010_tutorbankaccount_payoutrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutordetail',
            name='diploma_grade',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tutordetail',
            name='proficiency_test_grade',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
