# Generated by Django 4.2.6 on 2024-01-24 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_subject_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0011_alter_tutordetail_diploma_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=300, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorSubjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tutor-subject-document')),
                ('tutor_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.tutorsubject')),
            ],
        ),
    ]
