# Generated by Django 4.2.6 on 2024-01-26 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_tutorsubject_tutorsubjectdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutordetail',
            name='profile_picture',
        ),
    ]
