# Generated by Django 4.2.6 on 2024-02-08 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('tutor', '0013_remove_tutordetail_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorbankaccount',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.country'),
        ),
        migrations.AddField(
            model_name='tutorbankaccount',
            name='stripe_external_account_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
