# Generated by Django 4.2.6 on 2024-02-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0014_tutorbankaccount_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='expected_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
