# Generated by Django 4.2.6 on 2024-02-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0015_classroom_expected_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutordetail',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='curriculum-vitaes'),
        ),
        migrations.AlterField(
            model_name='tutordetail',
            name='proficiency_test_file',
            field=models.FileField(blank=True, null=True, upload_to='proficiency-test-files'),
        ),
    ]
