# Generated by Django 4.2.6 on 2024-02-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0016_tutordetail_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='reference',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed')], default='pending', max_length=100),
        ),
    ]
