# Generated by Django 4.2.6 on 2024-02-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0017_payoutrequest_reference_alter_payoutrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutordetail',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
