# Generated by Django 4.2.6 on 2024-02-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0018_alter_tutordetail_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutordetail',
            name='allow_intro_call',
            field=models.BooleanField(default=False),
        ),
    ]
