# Generated by Django 4.2.6 on 2024-02-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0019_tutordetail_allow_intro_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutordetail',
            name='max_hour_class_hour',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='tutordetail',
            name='allow_intro_call',
            field=models.BooleanField(default=True),
        ),
    ]
