# Generated by Django 4.2.6 on 2024-03-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0020_tutordetail_max_hour_class_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutordetail',
            name='high_school_attended',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tutordetail',
            name='high_school_subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
