# Generated by Django 4.2.6 on 2024-03-07 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0021_tutordetail_high_school_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('custom', 'Custom')], default='normal', max_length=50),
        ),
        migrations.AddField(
            model_name='tutorcalendar',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutor.classroom'),
        ),
    ]
