# Generated by Django 4.2.6 on 2024-03-07 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0023_tutordetail_proficiency_test_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutordetail',
            name='max_hour_class_hour',
        ),
    ]
