# Generated by Django 4.2.6 on 2024-03-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0024_remove_tutordetail_max_hour_class_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
