# Generated by Django 4.2.6 on 2024-03-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0025_alter_classroom_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorcalendar',
            name='classroom',
        ),
        migrations.AddField(
            model_name='tutorcalendar',
            name='classroom',
            field=models.ManyToManyField(to='tutor.classroom'),
        ),
    ]
