# Generated by Django 4.2.6 on 2024-03-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0027_classroom_meeting_id_classroom_student_joined_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutordetail',
            name='discipline',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tutordetail',
            name='university_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
