# Generated by Django 4.2.6 on 2024-05-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0033_classroom_student_complete_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutordetail',
            name='subjects',
        ),
    ]
