# Generated by Django 4.2.6 on 2024-05-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_testimonial_language'),
        ('tutor', '0034_remove_tutordetail_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutordetail',
            name='subjects',
            field=models.ManyToManyField(to='home.subject'),
        ),
    ]
