# Generated by Django 4.2.6 on 2024-05-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0035_tutordetail_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorbankaccount',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='tutorbankaccount',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='tutorbankaccount',
            name='account_type',
        ),
    ]
