# Generated by Django 4.2.6 on 2024-06-11 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_profile_stripe_verified'),
        ('tutor', '0036_remove_tutorbankaccount_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.transaction'),
        ),
    ]
