# Generated by Django 4.2.6 on 2024-06-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0037_payoutrequest_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutordetail',
            name='address_back_file',
            field=models.FileField(blank=True, null=True, upload_to='address-files'),
        ),
        migrations.AddField(
            model_name='tutordetail',
            name='address_front_file',
            field=models.FileField(blank=True, null=True, upload_to='address-files'),
        ),
    ]
