# Generated by Django 4.2.6 on 2024-06-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0038_tutordetail_address_back_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutordetail',
            name='nationality_back_file',
            field=models.FileField(blank=True, null=True, upload_to='nationality-files'),
        ),
        migrations.AddField(
            model_name='tutordetail',
            name='nationality_front_file',
            field=models.FileField(blank=True, null=True, upload_to='nationality-files'),
        ),
    ]
