# Generated by Django 4.2.6 on 2023-12-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_address_alter_profile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
