# Generated by Django 4.2.6 on 2024-01-07 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('home', '0004_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trasaction_type',
            field=models.CharField(choices=[('fund_wallet', 'Fund Wallet'), ('course_payment', 'Course Payment'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund')], default='fund_wallet', max_length=60),
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='EduDream', max_length=200, null=True)),
                ('escrow_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
    ]
