# Generated by Django 4.2.6 on 2024-01-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_transaction_trasaction_type_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('coin', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='class_grace_period',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='coin_threshold',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='enquiry_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_calendar_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_redirect_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
