# Generated by Django 4.2.6 on 2024-01-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_paymentplan_sitesetting_class_grace_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='class_grace_period',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
