# Generated by Django 4.2.6 on 2024-01-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_profile_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
    ]
