# Generated by Django 4.2.6 on 2024-01-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_profile_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='referral_coin',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('fund_wallet', 'Fund Wallet'), ('course_payment', 'Course Payment'), ('withdrawal', 'Withdrawal'), ('refund', 'Refund'), ('bonus', 'Bonus')], default='fund_wallet', max_length=60),
        ),
    ]
