# Generated by Django 4.2.6 on 2024-01-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_language_userlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='payout_coin_to_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
        ),
    ]
