# Generated by Django 4.2.6 on 2024-01-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_profile_city_alter_profile_state'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'city', 'state', 'country', 'referred_by'], name='home_profil_user_id_952cb7_idx'),
        ),
    ]
