# Generated by Django 4.2.6 on 2024-01-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_profile_home_profil_user_id_952cb7_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.CharField(choices=[('mid_school', 'Middle School'), ('high_school', 'High School')], default='mid_school', max_length=50),
        ),
    ]
