# Generated by Django 4.2.6 on 2024-02-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_notification_read_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_connect_account_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
