# Generated by Django 4.2.6 on 2024-02-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_paymentplan_descripttion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='zoom_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
