# Generated by Django 4.2.6 on 2024-02-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
