# Generated by Django 4.2.6 on 2024-03-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_notification_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
