# Generated by Django 4.2.6 on 2024-04-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_profile_approved_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='admin_initiated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='users_type',
            field=models.CharField(default='all', max_length=50, null=True),
        ),
    ]
