# Generated by Django 4.2.6 on 2024-04-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_notification_admin_initiated_notification_users_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='language',
        ),
    ]
