# Generated by Django 4.2.6 on 2024-06-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_profile_stripe_verified'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='home_profil_user_id_952cb7_idx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'state', 'country', 'referred_by'], name='home_profil_user_id_f81407_idx'),
        ),
    ]
