# Generated by Django 4.2.6 on 2024-06-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_profile_home_profil_user_id_952cb7_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='profile',
            name='home_profil_user_id_f81407_idx',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'city', 'state', 'country', 'referred_by'], name='home_profil_user_id_cfd069_idx'),
        ),
    ]
