# Generated by Django 4.2.6 on 2024-06-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_profile_home_profil_user_id_f81407_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_documents_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
