# Generated by Django 4.2.6 on 2024-09-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_profile_stripe_documents_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
