# Generated by Django 4.2.6 on 2023-12-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_address_alter_profile_account_type'),
        ('student', '0002_student_created_on_student_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='help_subject',
            field=models.ManyToManyField(to='home.subject'),
        ),
    ]
